version: "3.3"
services:
  backend:
    container_name: Backend
    restart: always
    build: ./server
    ports:
      - 8000:3001
  frontend:
    container_name: frontend
    build: ./client
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend

volumes:
  my-data:
